apiVersion: apps/v1
kind: Deployment
metadata:
  name: whoami-dep
  labels:
    app: whoami
spec:
  replicas: 2
  selector:
      matchLabels:
        app: whoami
  template:
    metadata:
      name: whoami
      labels:
        app: whoami
    spec:
      containers:
      - name: whoami-pod
        image: your-name-on-docker-hub/whoami:0.1.0
        ports:
          - containerPort: 5000
